name: "mnist_deploy"
op {
  input: "data"
  input: "conv1_w"
  input: "conv1_b"
  output: "conv1"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 5
  }
  arg {
    name: "exhaustive_search"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  engine: "CUDNN"
}
op {
  input: "conv1"
  output: "pool1"
  name: ""
  type: "MaxPool"
  arg {
    name: "kernel"
    i: 2
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 2
  }
  engine: "CUDNN"
}
op {
  input: "pool1"
  input: "conv2_w"
  input: "conv2_b"
  output: "conv2"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 5
  }
  arg {
    name: "exhaustive_search"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  engine: "CUDNN"
}
op {
  input: "conv2"
  output: "pool2"
  name: ""
  type: "MaxPool"
  arg {
    name: "kernel"
    i: 2
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 2
  }
  engine: "CUDNN"
}
op {
  input: "pool2"
  input: "fc3_w"
  input: "fc3_b"
  output: "fc3"
  name: ""
  type: "FC"
}
op {
  input: "fc3"
  output: "fc3"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  engine: "CUDNN"
}
op {
  input: "fc3"
  input: "pred_w"
  input: "pred_b"
  output: "pred"
  name: ""
  type: "FC"
}
op {
  input: "pred"
  output: "softmax"
  name: ""
  type: "Softmax"
  engine: "CUDNN"
}
external_input: "data"
external_input: "conv1_w"
external_input: "conv1_b"
external_input: "conv2_w"
external_input: "conv2_b"
external_input: "fc3_w"
external_input: "fc3_b"
external_input: "pred_w"
external_input: "pred_b"
